version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: linkedin-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkedin_jobs
    ports:
      - "5432:5432"
    networks:
      - scraper-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: linkedin-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge